# https://taskfile.dev

version: "3"

vars:
  #GITHUB: https://github.com/aws-samples/aws-batch-with-ffmpeg.git
  GITHUB: https://github.com/gmarchand/aws-batch-ffmpeg.git
  DATE:
    sh: date '+%d-%m-%Y'
tasks:  
  github:
    desc: build open source package
    cmds:
      - rm -rf dist/ || true
      - mkdir -p dist/archive/ dist/aws-batch-ffmpeg/
      - git tag -a "GITHUB_{{.DATE}}" -m "deployment on github"
      - git archive --format=tar HEAD | gzip > dist/opensource_{{.DATE}}.tar.gz
      - tar -zxvf dist/opensource_{{.DATE}}.tar.gz -C dist/archive
      - rm dist/opensource_{{.DATE}}.tar.gz
      - git clone {{.GITHUB}} dist/aws-batch-ffmpeg
      - cp -R dist/archive/* dist/aws-batch-ffmpeg/
      - cd dist/aws-batch-ffmpeg/ && git add . && git commit -m 'version {{.DATE}}' && git push || true
      - rm -rf dist/ || true

